plugins:
    - rubocop-rails
    - rubocop-performance
    - rubocop-rspec
    - rubocop-capybara
    - rubocop-rspec_rails

AllCops:
    TargetRubyVersion: 3.2
    NewCops: enable
    SuggestExtensions: false
    Exclude:
        - "db/schema.rb"
        - "bin/*"
        - "node_modules/**/*"
        - "vendor/**/*"

Style/Documentation:
    Enabled: false

Metrics/BlockLength:
    Exclude:
        - "db/queue_schema.rb"
